obj-y += comphy_core.o
obj-$(CONFIG_TARGET_ARMADA_38X) += comphy_a38x.o
obj-$(CONFIG_TARGET_ARMADA_8K) += comphy_ap806_z1.o
obj-$(CONFIG_TARGET_ARMADA_LP) += comphy_a3700.o
obj-y += comphy_pcie_config.o
