obj-$(CONFIG_MVEBU_COMPHY_SUPPORT) += comphy_core.o
obj-$(CONFIG_MVEBU_COMPHY_SUPPORT) += comphy_mux.o
obj-$(CONFIG_TARGET_ARMADA_38X) += comphy_a38x.o
obj-$(CONFIG_TARGET_ARMADA_38X) += comphy_a38x_pcie_config.o
obj-$(CONFIG_TARGET_ARMADA_8K) += comphy_ap806_z1.o
obj-$(CONFIG_TARGET_ARMADA_8K) += comphy_cp110.o
obj-$(CONFIG_TARGET_ARMADA_3700) += comphy_a3700.o
