# Copyright (C) 2017 Texas Instruments Incorporated - http://www.ti.com/
#
# SPDX-License-Identifier:	GPL-2.0+
#

ifdef CONFIG_ARCH_OCTEONTX2
obj-$(CONFIG_CMD_FAILSAFE) += octeontx2_cmds.o
obj-$(CONFIG_CMD_ETH) += eth_cmds.o
obj-$(CONFIG_CMD_MDIO_DBG) += mdio_dbg.o
endif
