#
# Copyright (C) 2016 Stefan Roese <sr@denx.de>
#
# SPDX-License-Identifier:	GPL-2.0+
#

obj-y = cpu.o
obj-y += clock.o
obj-$(CONFIG_MVEBU_EFUSE_SUPPORT) += efuse.o
obj-$(CONFIG_MVEBU_EFUSE_SUPPORT) += mbox.o
