
obj-$(CONFIG_MVEBU_CHIP_SAR) += chip_sar.o

ifdef CONFIG_AP806_Z_SUPPORT
obj-$(CONFIG_TARGET_ARMADA_8K) += ap806z_sar.o
else
obj-$(CONFIG_TARGET_ARMADA_8K) += ap806_sar.o
endif

obj-$(CONFIG_TARGET_ARMADA_8K) += cp110_sar.o
