#
# Copyright (C) 2016 Marvell International Ltd.
#
# SPDX-License-Identifier:	GPL-2.0
# https://spdx.org/licenses


obj-$(CONFIG_CMD_MVEBU_BUBT) += bubt.o
obj-$(CONFIG_CMD_MVEBU_RX_TRAINING) += rx_training.o
obj-$(CONFIG_CMD_MVEBU_AVS) += avs.o
obj-$(CONFIG_CMD_MVEBU_MAP) += map.o
obj-$(CONFIG_CMD_MVEBU_TSEN) += thermal.o
