#
# Copyright (C) 2016 Marvell International Ltd.
#
# SPDX-License-Identifier:	GPL-2.0
# https://spdx.org/licenses


obj-$(CONFIG_CMD_MVEBU_BUBT) += bubt.o
obj-$(CONFIG_CMD_MVEBU_HW_INFO) += hw_info.o
obj-$(CONFIG_CMD_MVEBU_EFUSE) += efuse.o
