# SPDX-License-Identifier: GPL-2.0
#
# Copyright (C) 2016 Marvell International Ltd.
#
# https://spdx.org/licenses


obj-$(CONFIG_CMD_MVEBU_BUBT) += bubt.o
obj-$(CONFIG_CMD_MVEBU_MV_GET_COUNTERS) += mv_get_counters.o
obj-$(CONFIG_CMD_MVEBU_RX_TRAINING) += rx_training.o
