obj-$(CONFIG_DM_SPI_NAND_FLASH)	+=	spi-nand-uclass.o
obj-$(CONFIG_DM_SPI_NAND_FLASH)	+=	spi_nand_flash_probe.o

obj-$(CONFIG_SPI_NAND)	+=	spi-nand-base.o
obj-$(CONFIG_SPI_NAND)	+=	spi-nand-cmd.o
obj-$(CONFIG_SPI_NAND_FLASH_MTD)	+=	spi-nand-mtd.o
