#
# Copyright (C) 2017 Marvell International Ltd.
#
# SPDX-License-Identifier:     GPL-2.0
# https://spdx.org/licenses
#

#
# Copyright (C) 2016 Stefan Roese <sr@denx.de>
#
# SPDX-License-Identifier:	GPL-2.0+
#
obj-y = cpu.o
obj-y += cache_llc.o
obj-y += clock.o
obj-y += soc.o
