#
# *****************************************************************************
#  Copyright (C) Marvell International Ltd. and its affiliates
# *****************************************************************************
# Marvell GPL License Option
# If you received this File from Marvell, you may opt to use, redistribute
# and/or modify this File in accordance with the terms and conditions of the
# General Public License Version 2, June 1991 (the "GPL License"), a copy of
# which is available along with the File in the license.txt file or by writing
# to the Free Software Foundation, Inc., 59 Temple Place, Suite 330, Boston,
# MA 02111-1307 or on the worldwide web at http://www.gnu.org/licenses/gpl.txt.
#
# THE FILE IS DISTRIBUTED AS-IS, WITHOUT WARRANTY OF ANY KIND, AND THE IMPLIED
# WARRANTIES OF MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE ARE
# EXPRESSLY DISCLAIMED.  The GPL License provides additional details about this
# warranty disclaimer.
# *****************************************************************************
#

obj-y += unit-info.o
obj-y += soc-init.o
obj-y += misc.o
obj-$(CONFIG_AURORA_TIMER) += timer_aurora.o
obj-$(CONFIG_MVEBU_CA9) += platform.o
obj-$(CONFIG_ADEC) += adec.o
