#/* SPDX-License-Identifier:    GPL-2.0
# *
# * Copyright (C) 2020 Marvell International Ltd.
# *
# * https://spdx.org/licenses
# */

obj-y	:= board.o smc.o soc-utils.o
obj-${CONFIG_TARGET_CN10K_A} += switch.o
obj-$(CONFIG_OF_LIBFDT) += board-fdt.o
