#
# (C) Copyright 2000-2004
# Wolfgang Denk, DENX Software Engineering, wd@denx.de.
#
# SPDX-License-Identifier:	GPL-2.0+
#

obj-y	:= armada8021-pxp.o
obj-y	+= board-info.o
obj-y	+= db-8210-info.o
obj-y	+= rd-8210-info.o
