obj-y += mvebu_ddr.o
obj-$(CONFIG_MVEBU_DUNIT_SUPPORT) += ddr_dunit.o
ifdef CONFIG_MVEBU_MK6_SUPPORT
obj-$(CONFIG_MVEBU_STATIC_SUPPORT) += ddr_mckinley6.o
obj-$(CONFIG_MVEBU_DYNAMIC_SUPPORT) += mckinley_ddr/
endif
