#
# ***************************************************************************
# Copyright (C) 2015 Marvell International Ltd.
# ***************************************************************************
# This program is free software: you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by the Free
# Software Foundation, either version 2 of the License, or any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
# ***************************************************************************
#

obj-$(CONFIG_CMD_MVEBU_MISC) += cmd_misc.o
obj-$(CONFIG_CMD_MVEBU_SAR) += cmd_sar.o
obj-$(CONFIG_CMD_MVEBU_FDT_CONFIG) += cmd_fdt_config.o
obj-$(CONFIG_CMD_MVEBU_MPP) += cmd_mpp.o
obj-$(CONFIG_CMD_MVEBU_BUBT) += cmd_bubt.o
obj-$(CONFIG_CMD_MVEBU_MSS_BOOT) += cmd_mss.o
obj-$(CONFIG_CMD_MVEBU_PHY_INDIRECT) += cmd_phy_indirect.o
obj-$(CONFIG_ENV_IS_IN_BOOTDEV) += env_bootdev.o
obj-$(CONFIG_CMD_MVEBU_HW_INFO) += cmd_hw_info.o
obj-$(CONFIG_CMD_MVEBU_EFUSE) += cmd_efuse.o
